import React from "react";
import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    lineHeight: 1.5,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 10,
    color: "#666",
    marginBottom: 16,
  },
  section: {
    marginBottom: 12,
  },
  body: {
    fontSize: 10,
    lineHeight: 1.6,
    marginBottom: 4,
  },
});

function ResumeDocument({ content, title }: { content: string; title: string }) {
  const lines = content.split("\n").filter(Boolean);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.subtitle}>Generated by ResumeAI</Text>
        </View>
        <View style={styles.section}>
          {lines.map((line, i) => (
            <Text key={i} style={styles.body}>
              {line}
            </Text>
          ))}
        </View>
      </Page>
    </Document>
  );
}

export async function generateResumePDF(content: string, filename: string): Promise<Buffer> {
  const doc = <ResumeDocument content={content} title={filename.replace(/-ResumeAI\.pdf$/, "")} />;
  const blob = await pdf(doc).toBlob();
  const arrayBuffer = await blob.arrayBuffer();
  return Buffer.from(arrayBuffer);
}

export async function generateCoverLetterPDF(content: string, title: string): Promise<Buffer> {
  const doc = <ResumeDocument content={content} title={`Cover Letter — ${title}`} />;
  const blob = await pdf(doc).toBlob();
  const arrayBuffer = await blob.arrayBuffer();
  return Buffer.from(arrayBuffer);
}
