import { Document, Packer, Paragraph, TextRun, HeadingLevel } from "docx";

export async function generateResumeDOCX(content: string, title: string): Promise<Buffer> {
  const lines = content.split("\n").filter(Boolean);

  const paragraphs = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.HEADING_1,
    }),
    new Paragraph({
      children: [new TextRun({ text: "Generated by ResumeAI", italics: true, size: 20 })],
      spacing: { after: 200 },
    }),
    ...lines.map(
      (line) =>
        new Paragraph({
          children: [new TextRun({ text: line, size: 22 })],
          spacing: { after: 80 },
        })
    ),
  ];

  const doc = new Document({
    sections: [{ properties: {}, children: paragraphs }],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}

export async function generateCoverLetterDOCX(content: string, title: string): Promise<Buffer> {
  const paragraphs = content.split("\n\n").filter(Boolean);

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: `Cover Letter — ${title}`,
            heading: HeadingLevel.HEADING_1,
          }),
          ...paragraphs.map(
            (p) =>
              new Paragraph({
                children: [new TextRun({ text: p, size: 22 })],
                spacing: { after: 200 },
              })
          ),
        ],
      },
    ],
  });

  return Buffer.from(await Packer.toBuffer(doc));
}
